// Code generated by protoc-gen-go.
// source: getLoginToken.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

protoc --go_out=. getLoginToken.proto

It is generated from these files:
	getLoginToken.proto

It has these top-level messages:
	GetLoginToken
	GetLoginTokenRtn
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GetLoginToken struct {
	ClientType       *string `protobuf:"bytes,1,req" json:"ClientType,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetLoginToken) Reset()         { *m = GetLoginToken{} }
func (m *GetLoginToken) String() string { return proto.CompactTextString(m) }
func (*GetLoginToken) ProtoMessage()    {}

func (m *GetLoginToken) GetClientType() string {
	if m != nil && m.ClientType != nil {
		return *m.ClientType
	}
	return ""
}

type GetLoginTokenRtn struct {
	TokenId          *string `protobuf:"bytes,1,req" json:"TokenId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetLoginTokenRtn) Reset()         { *m = GetLoginTokenRtn{} }
func (m *GetLoginTokenRtn) String() string { return proto.CompactTextString(m) }
func (*GetLoginTokenRtn) ProtoMessage()    {}

func (m *GetLoginTokenRtn) GetTokenId() string {
	if m != nil && m.TokenId != nil {
		return *m.TokenId
	}
	return ""
}
