// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

protoc --go_out=. login.proto

It is generated from these files:
	login.proto

It has these top-level messages:
	Login
	LoginRtn
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Login struct {
	ClientType       *string `protobuf:"bytes,1,opt" json:"ClientType,omitempty"`
	UserName         *string `protobuf:"bytes,2,req,name=userName" json:"userName,omitempty"`
	PassWord         *string `protobuf:"bytes,3,req,name=passWord" json:"passWord,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Login) Reset()         { *m = Login{} }
func (m *Login) String() string { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()    {}

func (m *Login) GetClientType() string {
	if m != nil && m.ClientType != nil {
		return *m.ClientType
	}
	return ""
}

func (m *Login) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *Login) GetPassWord() string {
	if m != nil && m.PassWord != nil {
		return *m.PassWord
	}
	return ""
}

type LoginRtn struct {
	Status           *string `protobuf:"bytes,1,req" json:"Status,omitempty"`
	Msg              *string `protobuf:"bytes,2,opt" json:"Msg,omitempty"`
	TokenId          *string `protobuf:"bytes,3,opt" json:"TokenId,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LoginRtn) Reset()         { *m = LoginRtn{} }
func (m *LoginRtn) String() string { return proto.CompactTextString(m) }
func (*LoginRtn) ProtoMessage()    {}

func (m *LoginRtn) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *LoginRtn) GetMsg() string {
	if m != nil && m.Msg != nil {
		return *m.Msg
	}
	return ""
}

func (m *LoginRtn) GetTokenId() string {
	if m != nil && m.TokenId != nil {
		return *m.TokenId
	}
	return ""
}
